# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Aeropuerto.proto for package ''

require 'grpc'
require './Aeropuerto_pb'

module Torre
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Torre'

    rpc :Aterrizar, Avion, AterrizarReply
    rpc :Despegar, Avion, DespegarReply
    rpc :Gate, Avion, Empty
    rpc :Salir, Avion, Empty
  end

  Stub = Service.rpc_stub_class
end
