# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Aeropuerto_pb2 as Aeropuerto__pb2


class TorresStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Despegar = channel.unary_unary(
        '/Torres/Despegar',
        request_serializer=Aeropuerto__pb2.Avion.SerializeToString,
        response_deserializer=Aeropuerto__pb2.Destino.FromString,
        )


class TorresServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Despegar(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TorresServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Despegar': grpc.unary_unary_rpc_method_handler(
          servicer.Despegar,
          request_deserializer=Aeropuerto__pb2.Avion.FromString,
          response_serializer=Aeropuerto__pb2.Destino.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Torres', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
