# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Aeropuerto.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Avion" do
    optional :aerolinea, :string, 1
    optional :codigo_avion, :string, 2
    optional :peso, :int32, 3
    optional :combustible, :int32, 4
    optional :torre_control_inicial, :string, 5
    optional :torre_control_destino, :string, 6
  end
  add_message "Destino" do
    optional :destino, :string, 1
  end
  add_message "AterrizarReply" do
    optional :espera, :int32, 1
  end
end

Avion = Google::Protobuf::DescriptorPool.generated_pool.lookup("Avion").msgclass
Destino = Google::Protobuf::DescriptorPool.generated_pool.lookup("Destino").msgclass
AterrizarReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("AterrizarReply").msgclass
